### ISSUE TITLE
Upgrade to 2.2.1

### ISSUE THREAD

**Issue by kjarnet** [webjars/jasmine#5]
I need the latest release of jasmine, currently version 2.2.1 for an upgrade of the jasmine-maven-plugin. It would be awesome if you could add this version.

**Comment by jamesward** [comment]
They haven't put a release for this up yet: https://github.com/jasmine/jasmine/tree/master/dist

Want to file an issue with them?

**Comment by kjarnet** [comment]
It seems 2.2.1 is just a fix in their bower-file, so the "standalone" release (which is what the dist-folder contains) would be identical to version 2.2.0, so you can use this version instead.
