### ISSUE TITLE
Could not read WebJar RequireJS config for: jasmine 2.4.1

### ISSUE THREAD

**Issue by amaury-d** [webjars/jasmine#7]
Hello,

The requirejs config for jasmine should be added.

Best regards.

**Comment by jamesward** [comment]
This will be released shortly as `2.4.1-1`.

**Comment by amaury-d** [comment]
Thanks!

On Tue, May 10, 2016 at 4:57 PM, James Ward <notifications@github.com>
wrote:

> This will be released shortly as 2.4.1-1.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/jasmine/issues/7#issuecomment-218184080>
>



-- 
Amaury Decrême
